#!/usr/bin/env node

/**
 * ╔══════════════════════════════════════════╗
 * ║        VELORA — Interactive Setup        ║
 * ║  Guides you through all env variables    ║
 * ╚══════════════════════════════════════════╝
 *
 * Run: node setup.js
 * It will create:  .env  (backend)
 *                  travel-frontend/.env  (frontend)
 */

const readline = require("readline");
const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

// ── colours ────────────────────────────────────────────────────────────────
const c = {
  reset: "\x1b[0m",
  bold: "\x1b[1m",
  dim: "\x1b[2m",
  cyan: "\x1b[36m",
  green: "\x1b[32m",
  yellow: "\x1b[33m",
  red: "\x1b[31m",
  magenta: "\x1b[35m",
  blue: "\x1b[34m",
  white: "\x1b[37m",
};

const B = (s) => `${c.bold}${s}${c.reset}`;
const G = (s) => `${c.green}${s}${c.reset}`;
const Y = (s) => `${c.yellow}${s}${c.reset}`;
const C = (s) => `${c.cyan}${s}${c.reset}`;
const D = (s) => `${c.dim}${s}${c.reset}`;
const M = (s) => `${c.magenta}${s}${c.reset}`;
const R = (s) => `${c.red}${s}${c.reset}`;

// ── rl helper ───────────────────────────────────────────────────────────────
const rl = readline.createInterface({ input: process.stdin, output: process.stdout });

function ask(prompt, defaultVal = "") {
  return new Promise((resolve) => {
    const hint = defaultVal ? D(` [${defaultVal}]`) : "";
    rl.question(`  ${C("❯")} ${prompt}${hint}: `, (ans) => {
      resolve(ans.trim() || defaultVal);
    });
  });
}

function section(title, emoji = "🔧") {
  const line = "─".repeat(48);
  console.log(`\n${c.cyan}${line}${c.reset}`);
  console.log(`  ${emoji}  ${B(title)}`);
  console.log(`${c.cyan}${line}${c.reset}`);
}

function tip(msg) {
  console.log(`  ${Y("ℹ")}  ${D(msg)}`);
}

function ok(msg) {
  console.log(`  ${G("✔")}  ${msg}`);
}

function warn(msg) {
  console.log(`  ${Y("⚠")}  ${Y(msg)}`);
}

// ── banner ──────────────────────────────────────────────────────────────────
function banner() {
  console.clear();
  console.log(`
${c.cyan}${c.bold}
  ██╗   ██╗███████╗██╗      ██████╗ ██████╗  █████╗
  ██║   ██║██╔════╝██║     ██╔═══██╗██╔══██╗██╔══██╗
  ██║   ██║█████╗  ██║     ██║   ██║██████╔╝███████║
  ╚██╗ ██╔╝██╔══╝  ██║     ██║   ██║██╔══██╗██╔══██║
   ╚████╔╝ ███████╗███████╗╚██████╔╝██║  ██║██║  ██║
    ╚═══╝  ╚══════╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
${c.reset}${c.dim}  Interactive Setup — creates your .env files automatically${c.reset}

  This script will ask you ${B("8 questions")} and create two files:
    ${G("•")} ${B(".env")}                    (backend)
    ${G("•")} ${B("travel-frontend/.env")}    (frontend)

  Press ${Y("Enter")} to keep any suggested default value.
  You can always re-run this script to update your config.
`);
}

// ── write helpers ───────────────────────────────────────────────────────────
function writeBackendEnv(vals) {
  const content = `# ─────────────────────────────────────────────
# VELORA — Backend Environment Variables
# Generated by setup.js — do not commit this file
# ─────────────────────────────────────────────

# Server
PORT=${vals.port}
FRONTEND_URL=${vals.frontendUrl}

# MongoDB
MONGO_URI=${vals.mongoUri}

# JWT  (keep this secret!)
JWT_SECRET=${vals.jwtSecret}

# Google Cloud API Key
# Enable: Places API, Distance Matrix API, Directions API
GOOGLE_API_KEY=${vals.googleApiKey}

# OpenWeatherMap
# Free key at: https://openweathermap.org/api
OPENWEATHER_API_KEY=${vals.weatherApiKey}

# Gmail (Nodemailer)
# Use an App Password — NOT your real Gmail password
# Setup: myaccount.google.com → Security → App Passwords
EMAIL_USER=${vals.emailUser}
EMAIL_PASS=${vals.emailPass}
`;
  fs.writeFileSync(path.join(__dirname, ".env"), content, "utf8");
}

function writeFrontendEnv(vals) {
  const content = `# ─────────────────────────────────────────────
# VELORA — Frontend Environment Variables
# Generated by setup.js — do not commit this file
# ─────────────────────────────────────────────

# URL of your running backend server
VITE_API_URL=${vals.backendUrl}
`;
  const dir = path.join(__dirname, "travel-frontend");
  if (!fs.existsSync(dir)) {
    warn("travel-frontend/ folder not found — skipping frontend .env");
    return;
  }
  fs.writeFileSync(path.join(dir, ".env"), content, "utf8");
}

// ── validation helpers ──────────────────────────────────────────────────────
function looksLikeMongoUri(s) {
  return s.startsWith("mongodb://") || s.startsWith("mongodb+srv://");
}

// ── main ────────────────────────────────────────────────────────────────────
async function main() {
  banner();

  // ── SECTION 1: Server basics ──────────────────────────────────────────────
  section("Server Basics", "🖥️");
  tip("These are usually fine as defaults for local development.");
  const port = await ask("Backend port", "3000");
  const frontendUrl = await ask("Frontend URL", "http://localhost:5173");
  const backendUrl = `http://localhost:${port}`;

  // ── SECTION 2: MongoDB ────────────────────────────────────────────────────
  section("MongoDB", "🍃");
  tip("Use MongoDB Atlas (free): https://cloud.mongodb.com");
  tip("Format: mongodb+srv://<user>:<password>@cluster.mongodb.net/velora");
  let mongoUri = "";
  while (!looksLikeMongoUri(mongoUri)) {
    mongoUri = await ask("MONGO_URI");
    if (!looksLikeMongoUri(mongoUri)) {
      warn('Must start with "mongodb://" or "mongodb+srv://" — try again.');
    }
  }

  // ── SECTION 3: JWT ────────────────────────────────────────────────────────
  section("JWT Secret", "🔑");
  const autoSecret = crypto.randomBytes(32).toString("hex");
  tip(`A strong secret has been auto-generated for you.`);
  tip("Hit Enter to use it, or paste your own.");
  const jwtSecret = await ask("JWT_SECRET", autoSecret);

  // ── SECTION 4: Google APIs ────────────────────────────────────────────────
  section("Google Cloud API Key", "🗺️");
  tip("1. Go to: https://console.cloud.google.com");
  tip("2. Create/select a project → APIs & Services → Credentials");
  tip("3. Create API key → restrict to: Places API, Distance Matrix, Directions");
  const googleApiKey = await ask("GOOGLE_API_KEY");

  // ── SECTION 5: OpenWeatherMap ─────────────────────────────────────────────
  section("OpenWeatherMap API Key", "🌤️");
  tip("Free tier is enough. Sign up at: https://openweathermap.org/api");
  tip("After signing up, your key is in 'My API keys'.");
  const weatherApiKey = await ask("OPENWEATHER_API_KEY");

  // ── SECTION 6: Gmail (Nodemailer) ─────────────────────────────────────────
  section("Gmail for Email Sending", "📧");
  tip("Velora sends: SOS alerts, login alerts, password reset emails.");
  tip("You MUST use a Gmail App Password (NOT your normal password):");
  tip("  myaccount.google.com → Security → 2-Step Verification → App Passwords");
  tip("  Generate one for 'Mail' and paste it below.");
  const emailUser = await ask("Gmail address (EMAIL_USER)");
  const emailPass = await ask("Gmail App Password (EMAIL_PASS)");

  // ── Confirm & write ───────────────────────────────────────────────────────
  section("Summary", "📋");
  const vals = { port, frontendUrl, backendUrl, mongoUri, jwtSecret, googleApiKey, weatherApiKey, emailUser, emailPass };

  console.log(`
  ${B("Backend .env will contain:")}
  ${D("PORT")}              ${G(port)}
  ${D("FRONTEND_URL")}      ${G(frontendUrl)}
  ${D("MONGO_URI")}         ${G(mongoUri.slice(0, 40) + "...")}
  ${D("JWT_SECRET")}        ${G("[generated / set]")}
  ${D("GOOGLE_API_KEY")}    ${G(googleApiKey ? googleApiKey.slice(0, 12) + "..." : R("⚠ empty"))}
  ${D("OPENWEATHER_KEY")}   ${G(weatherApiKey ? weatherApiKey.slice(0, 12) + "..." : R("⚠ empty"))}
  ${D("EMAIL_USER")}        ${G(emailUser || R("⚠ empty"))}
  ${D("EMAIL_PASS")}        ${G(emailPass ? "[set]" : R("⚠ empty"))}

  ${B("Frontend travel-frontend/.env will contain:")}
  ${D("VITE_API_URL")}      ${G(backendUrl)}
`);

  const confirm = await ask("Write files? (yes/no)", "yes");
  if (confirm.toLowerCase().startsWith("n")) {
    console.log(`\n  ${Y("Aborted. No files were written.")}\n`);
    rl.close();
    return;
  }

  writeBackendEnv(vals);
  writeFrontendEnv(vals);

  // ── Next steps ────────────────────────────────────────────────────────────
  section("You're all set! 🎉", "🚀");
  console.log(`
  ${B("Files created:")}
  ${G("✔")}  ${B(".env")}                  ← backend secrets
  ${G("✔")}  ${B("travel-frontend/.env")}  ← frontend API URL

  ${B("To start the project:")}

  ${D("# Terminal 1 — Backend")}
  ${C("node server.js")}          ${D("or")}  ${C("npx nodemon server.js")}

  ${D("# Terminal 2 — Frontend")}
  ${C("cd travel-frontend")}
  ${C("npm run dev")}

  ${D("# Install dependencies first if you haven't:")}
  ${C("npm install")}             ${D("(in project root)")}
  ${C("cd travel-frontend && npm install")}

  ${B("Optional — check your .env anytime:")}
  ${C("cat .env")}

  ${B("Re-run setup:")}
  ${C("node setup.js")}

`);

  rl.close();
}

main().catch((err) => {
  console.error(R(`\n  Error: ${err.message}\n`));
  rl.close();
  process.exit(1);
});
